version: '2'

services:
  microtransactionsmgtapi:
    container_name: microtransactionscommandhandler
    image: petprojects/micro-transactions-command-handler:${BUILD_VERSION}
    network_mode: bridge
    build:
      context: ./src/Mts.CommandHandler
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
