version: '2'

services:
  microtransactionsmgtapi:
    container_name: microtransactionsmgtapi
    image: petprojects/micro-transactions-mgt-api:${BUILD_VERSION}
    network_mode: bridge
    build:
      context: ./src/API
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
