version: '2'

services:
  microtransactionsmgtapi:
    container_name: microtransactionscommandhandler
    image: petprojects/micro-transactions-command-handler:${BUILD_VERSION}
    network_mode: bridge
    environment:
       - 'MTS_APP_SETTINGS_ConsulStoreConfiguration:Environment=${CONSUL_ENVIRONMENT}'
       - 'MTS_APP_SETTINGS_ConsulClientConfiguration:Address=${CONSUL_ADDRESS}'
    build:
      context: ./src/Mts.CommandHandler
      dockerfile: Dockerfile
      args:
        source: ${OUTPUT_PATH}
